# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoC8yCli < Formula
  desc "Cumulocity's unofficial command line tool"
  homepage "https://goc8ycli.netlify.app/"
  version "2.1.0"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/reubenmiller/go-c8y-cli/releases/download/v2.1.0/c8y_2.1.0_macOS_amd64.tar.gz"
      sha256 "d8de084c905684f1ba66864581b203bad276288b8323482cc5be9e550c08cf28"
    end
    if Hardware::CPU.arm?
      url "https://github.com/reubenmiller/go-c8y-cli/releases/download/v2.1.0/c8y_2.1.0_macOS_arm64.tar.gz"
      sha256 "bce345fa5dfc1aa8844556419531d4e25e900bb2b90e890d16692a0c50ab22ae"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/reubenmiller/go-c8y-cli/releases/download/v2.1.0/c8y_2.1.0_linux_amd64.tar.gz"
      sha256 "3505a57e2a1dc0ef3340759561414354ebc226a90bdf8851c72e134b3d994f9e"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/reubenmiller/go-c8y-cli/releases/download/v2.1.0/c8y_2.1.0_linux_armv6.tar.gz"
      sha256 "b188d779e1368e3c9951467dfc1609c82a87a4a79a54c912cc62320814869a14"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/reubenmiller/go-c8y-cli/releases/download/v2.1.0/c8y_2.1.0_linux_arm64.tar.gz"
      sha256 "f429771bb22b99182d833d01c1a27fe3abf3bbf290800a68d88f1b53b8d3548f"
    end
  end

  depends_on "git" => :optional
  depends_on "jq" => :optional
  depends_on "zsh" => :optional
  depends_on "bash" => :optional
  depends_on "fish" => :optional

  def install
    bin.install "bin/c8y"
    man1.install Dir["share/man/man1/*"]

    config_dir = etc/"go-c8y-cli"

    if config_dir.exist?
      # FileUtils.rm_r etc/"go-c8y-cli"
      system "git", "-C", config_dir, "pull", "--ff-only"
    else
      system "git", "clone", "--depth", "1", "https://github.com/reubenmiller/go-c8y-cli-addons.git", config_dir
    end

    # Add completions
    output = Utils.safe_popen_read({ "SHELL" => "bash" }, "#{bin}/c8y", "completion", "bash")
    (bash_completion/"c8y").write output
    output = Utils.safe_popen_read({ "SHELL" => "zsh" }, "#{bin}/c8y", "completion", "zsh")
    (zsh_completion/"_c8y").write output
    output = Utils.safe_popen_read({ "SHELL" => "fish" }, "#{bin}/c8y", "completion", "fish")
    (fish_completion/"c8y.fish").write output
  end

  def caveats; <<~EOS
    Please add the following to your shell profile to enable usage of "set-session" and other helpful c8y utility functions

    bash: ~/.bashrc

      source "#{etc}/go-c8y-cli/shell/c8y.plugin.sh"

    zsh: ~/.zshrc

      source "#{etc}/go-c8y-cli/shell/c8y.plugin.zsh"

    fish: ~/.config/fish/config.fish

      source "#{etc}/go-c8y-cli/shell/c8y.plugin.fish"

    powershell: ~/.config/powershell/Microsoft.PowerShell_profile.ps1
      . "#{etc}/go-c8y-cli/shell/c8y.plugin.ps1"

    You will also need to force reload of your profile:

      source <profile>
  EOS
  end

  test do
    system "#{bin}/c8y version --select version"
  end
end
